coupark/urls.py
from django.urls import path, include
from coupark import views

# Template URLs
app_name = 'coupark'

urlpatterns = [
    path('register/', views.register, name='register' ),
    path('user_login/', views.user_login, name='user_login'),
]

couparking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from coupark import views

urlpatterns = [
    path('', views.index, name='index' ),
    path("admin/", admin.site.urls),
    path('coupark/', include('coupark.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('reservations/', views.reservations, name='reservations'),
    path('book/<pk>', views.reserve, name='reserve'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

coupark/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from datetime import datetime
# Create your models here.

def validate_ParkingSpace_vehicle_type(value):
    if not (value == 'Car' or value == 'Motorbike'):
        raise value.ValidationError("Vehicle Type not allowed")

class ParkingSpace( models.Model ):
    
    name = models.CharField( max_length=15 )
    description = models.CharField( max_length=100 )
    active = models.BooleanField( default = True )
    vehicleType = models.CharField(max_length=15, validators=[validate_ParkingSpace_vehicle_type])

    def __str__(self):
        return str(self.name)

class Date( models.Model ):
    date = models.DateField()

    def __str__(self):
        return str(self.date)

class ParkingReservation( models.Model ):

    parkingSpace = models.ForeignKey(ParkingSpace, on_delete=models.CASCADE)
    user = models.ForeignKey( User, on_delete=models.CASCADE, blank=True, null=True )
    date = models.ForeignKey( Date, on_delete=models.CASCADE )

    def __str__(self):
        return  self.parkingSpace.name + ' ' + str(self.date.date)

coupark/forms.py
from django import forms
from django.contrib.auth.models import User
import re

# def company_mail(email):
 
#     regex = r'\b[A-Za-z0-9._%+-]+@coupa.com'

#     if (not re.fullmatch(regex, email)):
#         raise forms.ValidationError(u'Email addresses must belong to Coupa.')

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

coupark/views.py
from django.shortcuts import render
from coupark.forms import UserForm
from coupark.models import ParkingSpace, ParkingReservation, Date

# For login:
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def index( request ):

    lastDate = Date.objects.last()
    availableSpaces = ParkingReservation.objects.filter( date = lastDate )
    currentUserReservation = True if ParkingReservation.objects.filter( date = lastDate, user = request.user ) else False

    return render( request, 'coupark/index.html', {'spaces': availableSpaces, 'dateBooking': lastDate, 'hasReservation': currentUserReservation} )

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def reservations(request):
    lastDate = Date.objects.last()
    currentUserReservations = ParkingReservation.objects.filter(user=request.user)[::-1]

    return render( request, 'coupark/reservations.html', { 'currentUserReservations': currentUserReservations, 'dateBooking': lastDate} )

@login_required
def reserve(request, pk):
    #Handles reservation 
    
    lastDate = Date.objects.last()
    availableSpaces = ParkingReservation.objects.filter( date = lastDate )
    currentUserReservation = ParkingReservation.objects.filter( date = lastDate, user = request.user )

    if len(currentUserReservation) > 0 and currentUserReservation.get(id = pk) != None:
        ParkingReservation.objects.update_or_create(id = pk, defaults={'user':None})
        return HttpResponseRedirect(reverse('index'))

    if availableSpaces.filter( id = pk ) != None and len(currentUserReservation) == 0:
        ParkingReservation.objects.update_or_create(id = pk, defaults={'user':request.user})
        return HttpResponseRedirect(reverse('index'))
    

def register( request ):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            registered = True

            # Login registered users.

            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate( username=username, password=password )

            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('index'))
                else:
                    return HttpResponse('Account not active')
            else:
                print('Someone tried to log in and failed')
                print( f'Username {username} and Password {password}' )
                return HttpResponse( 'Invalid login details supplied!' )

        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render( request, 'coupark/registration.html', {'registered': registered, 'user_form': user_form,} )


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate( username=username, password=password )

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('Someone tried to log in and failed')
            print( f'Username {username} and Password {password}' )
            return HttpResponse( 'Invalid login details supplied!' )
    else:
        return render( request, 'coupark/login.html', {} )

templates/coupark/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" 
          content="width=device-width, 
                   initial-scale=1" />
    
    <title>CouParking</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}"/>
  </head>
  <body class="d-flex flex-column h-100">
 
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static "images/Logo.png" %}" alt="Logo" width="150" height="30" class="d-inline-block align-text-top">
          </a>
          
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active text-white" href="{% url 'reservations' %}">View Reservations</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active text-white" href="{% url 'logout' %}">Logout</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link active text-white" href="{% url 'coupark:register' %}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active text-white" href="{% url 'coupark:user_login' %}">Login</a>
                </li>
              {% endif %}
    
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main class="flex-shrink-0">
      <div class="container">

        <div style="margin-top:40px"></div>

        {% block body_block %}
        <!-- Anything outside of this will be inherited on all views -->
        {% endblock %}

        <div style="margin-top:40px"></div>
  
      </div>
    </main>

    <footer class="footer mt-auto py-5 bg-dark">
      <div class="container">
        <span class="text-white">
          <p class="float-end mb-1">
            <a href="#">Back to top</a>
          </p>
          <p class="mb-1">© CouParking, Logo by Nico, Name by Juanma, Code by Carlos & Gabo!</p>
          <p class="mb-0">Need Help? <a href="mailto:tiago.leal@coupa.com">Contact Tiago</a> or read our <a href="#">getting started guide</a>.</p>
        </span>
      </div>
    </footer>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

templates/coupark/index.html
{% extends "coupark/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <div class="container" >
    <h1>Hi, {{user.get_full_name}} Welcome to Couparking</h1>
    <h2>You are booking for: <b>{{dateBooking}}</b></h2> 
    <h3>
      Free parking spots are marked in <span style="color:#198754">green</span>, booked parking spots are marked in <span style="color:#ffc107">orange</span>.
    </h3>
    <h3>
      Reservations for the next day are up for booking <b>after 6pm (COT)</b> everyday. 
    </h3>
  </div>
</div>

<div style="margin-top:40px"></div>

{% if spaces %}

<div class="container">
  <div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          <h2>Cars</h2>
        </button>
      </h2>
      <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">
          <div class="album py-5 bg-light">
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for space in spaces %}
                  {% if space.parkingSpace.vehicleType == 'Car' %}
                    <div class="col">
                      <div class="card shadow-sm">
                        {% if space.user != None %}
                          <svg class="bd-placeholder-img card-img-top" fill="#ffc107" width="100%" height="150" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Reserved Spot" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>{{space.parkingSpace.name}}</title>
                            <rect width="100%" height="100%" class="bg-warning"></rect>
                            <text class="justify-content-center" x="40%" y="50%" fill="#eceeef" dy=".3em">Reserved</text>
                            <text class="justify-content-center" x="40%" y="30%" fill="#eceeef" dy=".3em">{{space.parkingSpace.name}}</text>
                          </svg>
                        {% else %}
                          <svg class="bd-placeholder-img card-img-top" fill="#198754" width="100%" height="150" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Reserved Spot" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>{{space.parkingSpace.name}}</title>
                            <rect width="100%" height="100%" class="bg-success"></rect>
                            <text class="justify-content-center" x="40%" y="50%" fill="#eceeef" dy=".3em">Available</text>
                            <text class="justify-content-center" x="40%" y="30%" fill="#eceeef" dy=".3em">{{space.parkingSpace.name}}</text>
                          </svg>
                        {% endif %}
                        <div class="card-body">
                          {% if space.user != None %}
                            <p class="card-text">Reserved by: {{space.user.get_full_name}}</p>
                            <p class="card-text">{{space.parkingSpace.name}} {{space.parkingSpace.description}}</p>
                          {% else %}
                            <p class="card-text">{{space.parkingSpace.name}} {{space.parkingSpace.description}}</p>
                          {% endif %}
                          <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                              {% if not hasReservation and space.user == None %}
                                <a class="btn btn-outline-success" href="book/{{space.id}}">Book</a>
                              {% elif hasReservation and user.id == space.user.id %}
                                <a class="btn btn-outline-warning" href="book/{{space.id}}">Unbook</a>
                              {% elif space.user != None %}
                                <a class="btn btn-warning disabled" href="#">Booked</a>
                              {% else %}
                                <a class="btn btn-info disabled" href="#">Available</a>
                              {% endif %}
                            </div>
                            <small class="text-muted">CouParking</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
          <h2>Motorcycles</h2>
        </button>
      </h2>
      <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">
          <div class="album py-5 bg-light">
            <div class="container">
              <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for space in spaces %}
                  {% if space.parkingSpace.vehicleType == 'Motorbike' %}
                    <div class="col">
                      <div class="card shadow-sm">
                        {% if space.user != None %}
                          <svg class="bd-placeholder-img card-img-top" fill="#ffc107" width="100%" height="150" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Reserved Spot" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>{{space.parkingSpace.name}}</title>
                            <rect width="100%" height="100%" class="bg-warning"></rect>
                            <text class="justify-content-center" x="40%" y="50%" fill="#eceeef" dy=".3em">Reserved</text>
                            <text class="justify-content-center" x="40%" y="30%" fill="#eceeef" dy=".3em">{{space.parkingSpace.name}}</text>
                          </svg>
                        {% else %}
                          <svg class="bd-placeholder-img card-img-top" fill="#198754" width="100%" height="150" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Reserved Spot" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>{{space.parkingSpace.name}}</title>
                            <rect width="100%" height="100%" class="bg-success"></rect>
                            <text class="justify-content-center" x="40%" y="50%" fill="#eceeef" dy=".3em">Available</text>
                            <text class="justify-content-center" x="40%" y="30%" fill="#eceeef" dy=".3em">{{space.parkingSpace.name}}</text>
                          </svg>
                        {% endif %}
                        <div class="card-body">
                          {% if space.user != None %}
                            <p class="card-text">Reserved by: {{space.user.get_full_name}}</p>
                            <p class="card-text">{{space.parkingSpace.name}} {{space.parkingSpace.description}}</p>
                          {% else %}
                            <p class="card-text">{{space.parkingSpace.name}} {{space.parkingSpace.description}}</p>
                          {% endif %}
                          <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                              {% comment %} Add Connections to view {% endcomment %}
                              {% if not hasReservation and space.user == None %}
                                <a class="btn btn-outline-success" href="book/{{space.id}}">Book</a>
                              {% elif hasReservation and user.id == space.user.id %}
                                <a class="btn btn-outline-warning" href="book/{{space.id}}">Unbook</a>
                              {% elif space.user != None %}
                                <a class="btn btn-warning disabled" href="#">Booked</a>
                              {% else %}
                                <a class="btn btn-info disabled" href="#">Available</a>
                              {% endif %}
                            </div>
                            <small class="text-muted">CouParking</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endif %}

<div style="margin-top:40px"></div>

{% endblock %}

templates/coupark/login.html
{% extends "coupark/base.html" %}
{% load static %}
{% block body_block %}

  <div class="container">
    <div class="jumbotron">
      <div class="container">
        <h2>Log in</h2>
        <h4>If you dont have an account you can create one <a href="{% url 'coupark:register' %}">here</a></h4>
        
        <div class="row mb-3"></div>

        <div class="container">
          <form action="{% url 'coupark:user_login' %}" method="POST" >
  
            {% csrf_token %}
            <div>
              <label for="username">Username:</label>
              <input type="text" name="username" placeholder="Enter you username">
            </div>
            <div class="row mb-2"></div>
            <div>
              <label for="password">Password:</label>
              <input type="password" name="password">
            </div>
    
            <input class="btn btn-primary" type="submit" value="Login">
    
          </form>
          <div class="row mb-5"></div>
        </div>
      </div>
    </div>
  </div>
  

{% endblock %}

templates/coupark/registration.html
{% extends "coupark/base.html" %}
{% load static %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">

    <div class="row mb-3" ></div>

    <div class="container">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here!</h1>

        <p>Please use your personal email.</p>
        <form enctype="multipart/form-data" method="POST" >

          {% csrf_token %}
          {{ user_form.as_p }}

          <input class="btn btn-primary" type="submit" value="Register">

        </form>
      {% endif %}

      <div class="row mb-5" ></div>
    </div>
  </div>
</div>

{% endblock %}

templates/coupark/reservations.html
{% extends "coupark/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <div class="container" >
    <h1>Hi, {{user.get_full_name}} this are your previous reservations.</h1>
    <h2>Currently you can book spots for the: {{dateBooking}}</h2>
  </div>
</div>

<div style="margin-top:40px"></div>

{% if currentUserReservations %}

<div class="overflow-auto">
  <div class="container">
    <ul class="list-group">
      
      <li class="list-group-item active" aria-current="true">
        <h5>Previous Reservations:</h5>
      </li>

      {% for reservation in currentUserReservations %}
        <li class="list-group-item">
          <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{reservation.parkingSpace.name}}</h5>
          <small>{{reservation.date.date}}</small>
          </div>
          <p class="mb-1">{{reservation.parkingSpace.description}}</p>
          <small>{{reservation.parkingSpace.vehicleType}}</small>
        </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% else %}

  <div class="container">
    <h4>You have no existing reservations.</h4>
    <a class="nav-link" href="{% url 'index' %}">Go back</a>
  </div>

{% endif %}
<div style="margin-top:40px"></div>

{% endblock %}